name: Demo

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - firefox
          - edge

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:16

    services:
      selenium:
        image: selenium/standalone-${{ github.event.inputs.browser }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run selenium
        env:
          BROWSER: ${{ github.event.inputs.browser }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/
      - run: |
          npx yatt-pipe \
            -c creds.json \
            -s results/mocha-results.xml \
            -T junit \
            -t yatt \
            -p